[package]
name = "vault-rpc-proxy"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
vault-core = { path = "../vault-core" }
tokio = { workspace = true, features = ["full", "sync"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
warp = "0.3"
reqwest = { version = "0.11", features = ["json"] }